# version: '3.8'

services:
  
  postgres:
    image: postgres:15
    restart: always
    env_file: 
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
  
  article-service:
    build:
      context: .
      dockerfile: HappyHeadlines.ArticleService/Dockerfile
    deploy:
      replicas: 2
    env_file:
      - ./HappyHeadlines.ArticleService/.env
    depends_on:
       postgres:
          condition: service_healthy
                
  draft-service:
    build:
      context: .
      dockerfile: HappyHeadlines.DraftService/Dockerfile
    deploy:
      replicas: 2 # amount of instances
    env_file:
        - ./HappyHeadlines.DraftService/.env
    depends_on:
        postgres:
          condition: service_healthy
          
          
  comment-service:
    build:
      context: .
      dockerfile: HappyHeadlines.CommentService/Dockerfile
    deploy:
      replicas: 2
    env_file:
        - ./HappyHeadlines.CommentService/.env
    depends_on:
        postgres:
          condition: service_healthy
          
  profanity-service:
    build:
      context: .
      dockerfile: HappyHeadlines.ProfanityService/Dockerfile
    deploy:
      replicas: 1
    depends_on:
        postgres:
          condition: service_healthy
    volumes:
      - profanity-data:/app/data
  
  publisher-service:
    build:
      context: .
      dockerfile: HappyHeadlines.PublisherService/Dockerfile
    deploy:
      replicas: 1
    env_file:
        - ./HappyHeadlines.PublisherService/.env
    depends_on:
      - message-broker

  subscriptions-service:
    build:
      context: .
      dockerfile: HappyHeadlines.NewsletterService/Dockerfile
    environment:
      #ASPNETCORE_URLS: http://+:8080
      # SQLite-fil i en skrivbar mappe
      ConnectionStrings__db: Data Source=/app/data/newsletter.db;Cache=Shared;Mode=ReadWriteCreate
      # RabbitMQ (via service-navn)
      Rabbit__Host: message-broker
      Rabbit__User: guest
      Rabbit__Pass: guest
      # Mail
      Email__From: no-reply@happyheadlines.local
      Email__Smtp__Host: mailhog
      Email__Smtp__Port: "1025"
    volumes:
      - ./data:/app/data 
    depends_on:
      - message-broker
      - mailhog

     
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"     # SMTP
      - "8025:8025"     # UI

  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - happy-headlines-data:/var/lib/rabbitmq
        
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - article-service
      - draft-service
      - comment-service
      - profanity-service
      - hh-webapp
      - subscriptions-service

  hh-webapp:
   build:
    context: .
    dockerfile: HappyHeadlines.WebApp/HappyHeadlines.WebApp/Dockerfile

  c4:
    image: structurizr/lite:latest
    ports:
      - "18080:8080"
    volumes:
      - ./docs:/usr/local/structurizr
    # valgfrit: sæt en base URL hvis du vil linke ind fra README
    environment:
      - STRUCTURIZR_WORKSPACE_PATH=/usr/local/structurizr/workspace.dsl

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    volumes:
      - happy-headlines-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
        
volumes:
  postgres-data:
  happy-headlines-data:
  profanity-data:
  newsletter-data: {}  