version: "3.9"

services:
  articleservice:
    image: happyheadlines-webapi:latest
    build:
      context: ./HappyHeadlines.WebApi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 3
