version: '3.8'

services:
  article-service:
    build:
      context: .
      dockerfile: HappyHeadlines.ArticleService/Dockerfile 
    deploy:
      replicas: 3 # amount of instances
    environment:
      - ConnectionStrings__Global=Host=db-global;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Europe=Host=db-europe;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Asia=Host=db-asia;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Africa=Host=db-africa;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__NorthAmerica=Host=db-northamerica;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__SouthAmerica=Host=db-southamerica;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Oceania=Host=db-oceania;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Antarctica=Host=db-antarctica;Port=5432;Database=articles;Username=user;Password=pass
                
  draft-service:
    build:
      context: .
      dockerfile: HappyHeadlines.DraftService/Dockerfile
    deploy:
      replicas: 3 # amount of instances
    environment:
      - ConnectionStrings__Global=Host=db-global;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Europe=Host=db-europe;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Asia=Host=db-asia;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Africa=Host=db-africa;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__NorthAmerica=Host=db-northamerica;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__SouthAmerica=Host=db-southamerica;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Oceania=Host=db-oceania;Port=5432;Database=articles;Username=user;Password=pass
      - ConnectionStrings__Antarctica=Host=db-antarctica;Port=5432;Database=articles;Username=user;Password=pass
  
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y