version: '3.8'

services:
  article-service:
    build:
      context: .
      dockerfile: HappyHeadlines.ArticleService/Dockerfile 
    deploy:
      replicas: 3 # amount of instances
    environment:
      - ConnectionStrings__Global=${GLOBAL_CONNECTION_STRING}
      - ConnectionStrings__Europe=${EUROPE_CONNECTION_STRING}
      - ConnectionStrings__Asia=${ASIA_CONNECTION_STRING}
      - ConnectionStrings__Africa=${AFRICA_CONNECTION_STRING}
      - ConnectionStrings__NorthAmerica=${NORTHAMERICA_CONNECTION_STRING}
      - ConnectionStrings__SouthAmerica=${SOUTHAMERICA_CONNECTION_STRING}
      - ConnectionStrings__Oceania=${OCEANIA_CONNECTION_STRING}
      - ConnectionStrings__Antarctica=${ANTARCTICA_CONNECTION_STRING}
                
  draft-service:
    build:
      context: .
      dockerfile: HappyHeadlines.DraftService/Dockerfile
    deploy:
      replicas: 3 # amount of instances
    environment:
      - ConnectionStrings__Global=${GLOBAL_CONNECTION_STRING}
      - ConnectionStrings__Europe=${EUROPE_CONNECTION_STRING}
      - ConnectionStrings__Asia=${ASIA_CONNECTION_STRING}
      - ConnectionStrings__Africa=${AFRICA_CONNECTION_STRING}
      - ConnectionStrings__NorthAmerica=${NORTHAMERICA_CONNECTION_STRING}
      - ConnectionStrings__SouthAmerica=${SOUTHAMERICA_CONNECTION_STRING}
      - ConnectionStrings__Oceania=${OCEANIA_CONNECTION_STRING}
      - ConnectionStrings__Antarctica=${ANTARCTICA_CONNECTION_STRING}
  
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y