// <auto-generated />
using HappyHeadlines.ProfanityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyHeadlines.ProfanityService.Migrations
{
    [DbContext(typeof(ProfanityDbContext))]
    [Migration("20250930171241_addProfanityData")]
    partial class addProfanityData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HappyHeadlines.ProfanityService.Data.ProfanityWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProfanityWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "badword1"
                        },
                        new
                        {
                            Id = 2,
                            Word = "badword2"
                        },
                        new
                        {
                            Id = 3,
                            Word = "badword3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
